keys:
    - &elysium age1f6krx9zxft5lwn9va4gy4e2hl8x3eahdcyn6f32way4cvep32v7qpkch6a
    - &aria age1uqd4xcechah5zy2q90fd0t42plssnnua2fgfuw0806f9tr8qmdys4gxwvp
    - &grendel age1qrupvhqhlv3c8qfgz42fwkqzfp8w4hgha5jr93yyd8jv42cun49qmznf94
creation_rules:
  - path_regex: modules/k3s/secrets.ya?ml$
    key_groups:
      - age:
         - *aria
         - *elysium
  - path_regex: modules/mediacenter/deluge.txt
    key_groups:
      - age:
         - *grendel