keys:
    - &dev01 age1f6krx9zxft5lwn9va4gy4e2hl8x3eahdcyn6f32way4cvep32v7qpkch6a
    - &aria age1yphy826yw6e0lnlnnejwgkwp9ytfkaegpzhtj0e2h9gksswj0y7q8m9gxr
creation_rules:
  - path_regex: modules/k3s/secrets.ya?ml$
    key_groups:
      - age:
         - *dev01
         - *aria